#!/bin/python

from flask import Flask, request, abort
import os, json

app = Flask(__name__)

@app.route('/deploy', methods=['POST'])
def webhook():
   if request.method == 'POST':
       payload = request.get_json()
       ref = payload['ref']
       if '/master' in ref:
           os.system('kubectl rollout restart deployment/backend')
           return 'Deployement updated!\n', 200
       return 'Push is not on master\n', 200
   else:
      abort(400)

if __name__ == '__main__':
    app.run()
