#!/bin/ruby

require 'sinatra'
require 'json'

post '/deploy' do
  request.body.rewind
  payload_body = request.body.read
  verify_signature(payload_body)
  system('kubectl rollout restart deployment/backend')
  "Deploy successful!"
end

def verify_signature(payload_body)
  signature = 'sha256=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), ENV['SECRET_KEY'], payload_body)
  return halt 500, "Signatures didn't match!" unless Rack::Utils.secure_compare(signature, request.env['HTTP_X_HUB_SIGNATURE_256'])
end